services:
  - type: web
    name: shl-assessment-recommender
    runtime: docker
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: groq
    healthCheckPath: /health
    buildCommand: ""
    startCommand: ""
